#!/bin/bash
cd "$(dirname "$0")" || exit

# Preload GTK4 Layer Shell to fix linking order issue with libwayland
# See: https://github.com/wmww/gtk4-layer-shell/blob/main/linking.md
export LD_PRELOAD=/usr/lib/libgtk4-layer-shell.so

exec gjs -m src/main.js "$@"
